### ISSUE TITLE
Maximum function nesting level error

### ISSUE THREAD

**Issue by pixleight** [barrelstrength/sprout-email#172]
### Description (screenshots, logs, ...)
An email notification is being triggered when an entry is updated and a field has a particular value. (Send rule: `{{ object.innovationStatus == 'published' }}`)

Some of these notifications have failed with the error "Maximum function nesting level of '256' reached, aborting!" While I've been able to track the error down to `xdebug.max_nesting_level`, though testing increasing the value much higher hasn't fixed the issue.

The email recipient fields are:

**To:** `{{ object.professor.one().email }}`

**CC:** `{% for author in object.authors.all() %}{{ author.email }}{% if not loop.last %}, {% endif %}{% endfor %}{% for professor in object.professor %}{% if not loop.first %}, {{ professor.email }}{% endif %}{% endfor %}`

**BCC:** `{% for interviewee in object.interviewee.all() %}{{ interviewee.emailAddress }}{% if not loop.last %}, {% endif %}{% endfor %}`

`authors` and `professor` are user fields, and `interviewee` is a matrix field.

In my test entry, `professor` has 2 users, `authors` has 4 users, and `interviewee` has 2 matrix blocks.

Removing one of the groupings of recipients from the email allows it to send.

Stacktrace: https://pastebin.com/pAwb9WAv

### Steps to reproduce

1. Create an entry with the above fields
2. Create an email notification with the event to trigger when entry is updated and send rule is `{{ object.innovationStatus == 'published' }}`
3. Save the entry, updating the field `innovationStatus` to be "published" to trigger the send event.

### Additional info

- Craft version: Craft Pro 3.3.8
- PHP version: 7.2.22
- Database driver & version:  MySQL 5.7.26
- Plugins & versions:  
Amazon S3	1.2.5
Delete Account	1.0.2
Element API	2.6.0
Environment Label	3.1.5
Express Forms	1.0.4
Guest Entries	2.2.4
Mailchimp Subscribe	3.0.0
Navigation	1.1.13
Neo	2.5.3
Position Fieldtype	1.0.14
reCAPTCHA	1.5.0
Redactor	2.4.0
Retour	3.1.26
Section Field	1.1.0
SendGrid	1.2.2
SEOmatic	3.3.8
**Sprout Email	4.0.5**
Sprout Reports	1.2.8
Template Comments	1.1.2
Typogrify	1.1.18
User Group Fixer	1.0.0
UserPhotoImporter	1.0.0
Video Embedder	1.1.4

**Comment by BenParizek** [comment]
@pixleight This sounds like an environment issue so I think you're on the right track looking into the nesting level setting. This error usually comes up on layouts with Matrix fields or highly relational content so that is consistent with this likely being an environment setting issue too.

And good test with removing the CC and BCC queries to confirm that it is working without those.

I think this may come down to addressing the`max_nesting_level` setting (and servers are not my strong suit) or how to optimize those queries ahead of time by going around the Element API which can add a lot of overhead.

While I haven't tested this, you could potentially try to create a query object and directly query the db for the data you want. It may get a bit messy with the data you want being in a Matrix field, but with the right IDs you could probably get things joined and queried in a lot lighter fashion:

```
{% set query = create('craft\\db\\Query') %}
{% for interviewee in query.select('*')
    .from('interviewee')
    .where({
        elementId: object.elementId,
        siteId: object.siteId
    })
    .all() %}
  {{ interviewee.emailAddress }}{% if not loop.last %}, {% endif %}
{% endfor %}
```

You'd likely also have to join the element tables and filter out drafts and revisions in that query, but it will still end up a lot lighter than going through the element API if you can't sort out the `max_nesting_level` setting
